### ISSUE TITLE
Can't set httpOnly=true for the iPlanetDirectoryPro cookie

### ISSUE THREAD

**Issue by IvanAndrukh** [OpenIdentityPlatform/OpenAM#193]
**Describe the bug**
I've tried to turn on httpOnly from admin panel(com.sun.identity.cookie.httponly=true) but it doesn't help. How can I set httpOnly to the 'true'? 

**Expected behavior**
HttpOnly flag is turned on for the iPlanetDirectoryPro cookie 

**Additional context**
Here is the screenshot. 
![image_2019_10_10T16_28_26_907Z](https://user-images.githubusercontent.com/26621751/66598658-28069b00-ebaa-11e9-9da6-bef93da5cee7.png)

**Comment by maximthomas** [comment]
Seems there is an issue with XUI, it can't create http only cookie by design, I'll try to figure out how to fix this.

**Comment by IvanAndrukh** [comment]
Please, notify when you resolve this issue.

**Comment by akshay141095** [comment]
Please notify when the issue is resolved

**Comment by vharseko** [comment]
XUI, it can't create http only cookie by design

**Comment by bhargavabada** [comment]
> XUI, it can't create http only cookie by design

is there any work around to enable Http Only flag in OpenAM 13.5.2 without disabling XUI .

**Comment by maximthomas** [comment]
Unfortunately, not yet.

**Comment by bhargavabada** [comment]
> Unfortunately, not yet.
thanks for the quick reply .

**Comment by bhargavabada** [comment]
> Unfortunately, not yet.

Can we set this flag true for federated module  authentication . SAML federation does not require XUI interaction . Any enhancement or post Authentication federation module  can we set the http only flag .

**Comment by vharseko** [comment]
use
``` 
-Dcom.sun.identity.cookie.httponly=true
```

**Comment by EkaLinMan** [comment]
Hi @vharseko @maximthomas, sorry to comment on a closed issue, but I’d like to clarify a few design/behavior questions around cookies in the context of the SAML flows.

Our Environment:
Product: OpenAM 14.6.4 (Open Identity Platform Community)
UI: XUI Interface

Questions:
1) Why does XUI not support `HttpOnly`?

OIP docs mention that XUI does not currently support `HttpOnly` cookies. Is it because XUI needs to read/write cookies via JavaScript? Does this limitation also apply to cookies used in **SAML SSO/SLO flows** when XUI is enabled?

2) You previously suggested using `-Dcom.sun.identity.cookie.httponly=true`. What exactly does it do, and how should it be applied?

Is it expected to affect cookies set by the server via `Set-Cookie`, or also cookies that may be written client-side by JavaScript during the **SAML SSO/SLO flows**? What is the recommended way to apply it (JVM `-D` vs Server Defaults > Advanced)?

3) Why is `iPlanetDirectoryPro` missing `SameSite` even when `SameSite` is configured?

We configured `org.openidentityplatform.openam.cookie.samesite=Strict` (OpenAM server property) and also set `sameSiteCookies="Strict"` in the Tomcat container's `context.xml`. However, we noticed that in the browser, the `SameSite` attribute for the `iPlanetDirectoryPro` cookie still appears empty during the flows. Is this intentional behavior? BTW, the `amlbcookie` correctly reflects the `Strict` setting after applying these configurations.

**Comment by maximthomas** [comment]
1. This is due to the implementation of the admin console. It needs to read cookies using JavaScript.

2. JavaScript cannot set the HttpOnly attribute; this attribute can only be set by server-side cookies.
JVM `-D` options have higher priority compared to Server Defaults → Advanced settings.

3. Check the HAR log in your browser. The Set-Cookie header should look something like this:
`iPlanetDirectoryPro=AQIC5wM2LY4Sfcw1vhTGf6uwaD4JDB7ggtPCXMcrQ_ypIRQ.*AAJTSQACMDEAAlNLABQtMTQ4NjQyMzg2Mzg`. The SameSite attribute for the iPlanetDirectoryPro cookie could be empty because a browser can ignore this flag for insecure connections. https://mdn2.netlify.app/en-us/docs/web/http/headers/set-cookie/samesite/

**Comment by EkaLinMan** [comment]
Hi @maximthomas, thanks for your reply, to clarify:

1) When SAML SSO triggers interactive login via XUI, does it mean **none** of the OpenAM cookies used during the SAML flow can be `HttpOnly`, or are server-set cookies (via `Set-Cookie`) still able to be `HttpOnly`?

2) If we set `com.sun.identity.cookie.httponly=true` (Server Defaults > Advanced, or via JVM `-D`) while still using XUI, is that a supported/safe configuration (i.e., it won’t break the admin console / XUI / SAML flows)?

3) We checked the HAR for the full SAML SSO/SLO flow and noticed that `iPlanetDirectoryPro` is not created via a `Set-Cookie` header during login; it just appears in subsequent requests, while during logout it is cleared via `Set-Cookie` (Max-Age=0). Does this mean `iPlanetDirectoryPro` is intentionally written client-side by XUI (which would explain why it cannot be `HttpOnly`, as discussed in this thread, and why `SameSite` may appear empty)?

**Comment by maximthomas** [comment]
Hi @EkaLinMan 
1. If you should use XUI for authentication, you should disable the `HttpOnly` flag for cookies
2. No, the admin console won't function properly
3. No, the `iPlanetDirectoryPro` cookie is set only by server.

**Comment by EkaLinMan** [comment]
Hi @maximthomas , thanks for your reply.

In our latest login trace, we still do not see a login-stage `Set-Cookie` response for `iPlanetDirectoryPro`.

However, the XUI bundle appears to contain a `SessionToken` flow that writes `iPlanetDirectoryPro` via `document.cookie` after receiving `tokenId`.

Also, in our runtime check, `cookieSameSite()` evaluates to `undefined` in `SessionToken.js`, and `CookieHelper.js` only accepts six parameters, so `SameSite` does not appear to be applied in this path.

Could you help clarify whether this could explain why `iPlanetDirectoryPro` often appears without a `SameSite` attribute in XUI-based authentication flows?

Has this behavior changed in a later OpenAM/OIP version or another branch (we're using 14.6.4), so that iPlanetDirectoryPro is now set entirely server-side?

<img width="1855" height="682" alt="Image" src="https://github.com/user-attachments/assets/79f2558c-8e33-4ffe-a3d1-b7ff11a90255" />
<img width="1854" height="657" alt="Image" src="https://github.com/user-attachments/assets/6eccdc64-bb50-4ad4-8975-ff56aa7bd2ec" />

**Comment by maximthomas** [comment]
Hi @EkaLinMan, thanks for pointing this out.
I think there’s an issue in the client libraries. I’ll create a fix soon.

**Comment by maximthomas** [comment]
Created a new issue #965

**Comment by vharseko** [comment]
try [16.0.6](https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/16.0.6)
