### ISSUE TITLE
OAuth Device Flow code generation LDAP search performance

### ISSUE THREAD

**Issue by muczy** [OpenIdentityPlatform/OpenAM#482]
**Describe the bug**
We have an OpenAM + OpenDJ (JE backend engine) setup (on different boxes) with ~1M users, various authentication methods and OAuth Device Flow. While other OAuth functions work, device flow hogs the system and times out after 10 seconds. We narrowed down the problem to the OpenAM code piece StatefulTokenStore.createDeviceCode() which tries to find out if the given code has already been used and if yes, generated a new one. Now this check is extremely costly via LDAP for this size of data.

**To Reproduce**
1. Setup OpenAM + OpenDJ with OAuth
2. Create 1M users
3. Try to run device flow using http://openam:8080/openam/oauth2/device/code

**Expected behavior**
The device flow response is returned (user_code, device_code...).

**Server (please complete the following information):**
 - OS: Linux + Docker

**Additional context**
Other functions (login, registration) continues to work with this size of data, only device flow seems to blocked by the issue. If there is a way to easily (without OpenAM code modification) remove this LDAP search based check, please tell me about it (writing a custom OAuth ScopeValidator is something I'm familiar with, so if something like this can be done to workaround the issue, I would be happy with it).

**Comment by vharseko** [comment]
please provide LDAP access log

**Comment by vharseko** [comment]
cannot reproduce

**Comment by vharseko** [comment]
Please create jstack 11 апр. 2022 г. 23:21 пользователь Peter Mihaly Avramucz ***@***.***> написал:
Describe the bug
We have an OpenAM + OpenDJ (JE backend engine) setup (on different boxes) with ~1M users, various authentication methods and OAuth Device Flow. While other OAuth functions work, device flow hogs the system and times out after 10 seconds. We narrowed down the problem to the OpenAM code piece StatefulTokenStore.createDeviceCode() which tries to find out if the given code has already been used and if yes, generated a new one. Now this check is extremely costly via LDAP for this size of data.
To Reproduce
Steps to reproduce the behavior:
Setup OpenAM + OpenDJ with OAuthCreate 1M usersTry to run device flow using http://openam:8080/openam/oauth2/device/code
Expected behavior
The device flow response is returned (user_code, device_code...).
Server (please complete the following information):
OS: Linux + Docker
Additional context
Other functions (login, registration) continues to work with this size of data, only device flow seems to blocked by the issue. If there is a way to easily (without OpenAM code modification) remove this LDAP search based check, please tell me about it (writing a custom OAuth ScopeValidator is something I'm familiar with, so if something like this can be done to workaround the issue, I would be happy with it).
