### ISSUE TITLE
Docker file issue

### ISSUE THREAD

**Issue by ghost** [OpenIdentityPlatform/OpenAM#721]
Based on your given docker file I have followed the steps. but given github url is not hitting and the url is 404 .  Can you please help me to take docker build and deploy and check.

**Comment by maximthomas** [comment]
@sundarrajan13 could you please provide more details? What manual are you following? What link gives you 404 error?

**Comment by vharseko** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by ghost** [comment]
based on   the docker file I'm using.
Below mentioned url is showing 404 error.
 curl -L
https://github.com/OpenIdentityPlatform/OpenAM/releases/download/$VERSION/OpenAM-$VERSION.war
--output $CATALINA_HOME/webapps/$OPENAM_PATH.war  \

**Comment by vharseko** [comment]
try 
```
docker run --rm -it -h openam-01.domain.com -p 8080:8080 --name openam-01 openidentityplatform/openam
```
