### ISSUE TITLE
After add new script: scripts page show message "No results to display"

### ISSUE THREAD

**Issue by barramandi** [OpenIdentityPlatform/OpenAM#85]
OpenAM version 14.1.8 (OpenAM 14.1.8 Build 900d6316b5 )

Scripts not viewable in management console.

**Comment by vharseko** [comment]
Switch to XUI (top and right)

**Comment by gt-khoo** [comment]
Already in XUI but scripts won't show. 
Tested with latest Chrome/Firefox.

**Comment by vharseko** [comment]
please provide details:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Comment by gt-khoo** [comment]
To Reproduce
**Steps to reproduce the behavior:**
1) Login to /sso/console
2) Click on Top Level Realm
3) Click on Scripts on left hand menu
4) Scripts page show message "No results to display"

**Expected behavior**
A list of default scripts should appear. i.e oidc claims, authentication client side, authentication server side ..etc

**Screenshots**
https://drive.google.com/open?id=1nbhlEAGN5dSbM-NP8BiqFHG96_A3LNKw

**Desktop (please complete the following information):**
    OS: Windows 8.1
    Browser Chrome  / Firefox
    Version  68.0.3440.106 / 62.0 (64-bit)

**Comment by vharseko** [comment]
Steps to reproduce the behavior:

1. Login to XUI
2. Click on Top Level Realm
3. Click on Scripts on left hand menu
4. Add new script
5. Scripts page show message "No results to display"

**Comment by gt-khoo** [comment]
Add new script also doesn't show.
But I verified the newly created scripts are present in configuration store (with LDAP browser).

**Screenshot**
https://drive.google.com/open?id=1Ap3BOLxXSHb9EnskePgHQGdI2QAVpKUU

**Comment by vharseko** [comment]
https://github.com/OpenIdentityPlatform/OpenAM/releases/tag/14.1.10
